# Generated by Django 4.2.11 on 2024-03-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategory_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='friendly_second_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='second_name',
        ),
    ]
