# Generated by Django 4.2.11 on 2024-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_friendly_second_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
