# Generated by Django 4.2.11 on 2024-04-28 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_discountproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False, help_text='Leave this checkbox empty, it will be set to True if a discount is set'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='The percentage of the discount applied to the product. (1-100)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave this field empty, it will be calculated based on the product price', max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text='(e.g. 0,30 if 0.30%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in SEK', max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, help_text='Leave this field empty, it will be set when creating the product', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Leave this field empty, it will be set when creating the product', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(help_text='Volume in ml', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
