# Generated by Django 4.2.11 on 2024-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave this field empty, it will be set later', max_digits=7, null=True),
        ),
    ]
