# Generated by Django 4.2.11 on 2024-06-27 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Write the name in all lower case, no special characters and use - as blank spaces', max_length=100),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='The percentage discount applied to the product (e.g. 25 will give a 25% discount)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='bitterness',
            field=models.IntegerField(help_text='On a scale from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=models.IntegerField(help_text='On a scale from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sweetness',
            field=models.IntegerField(help_text='On a scale from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(help_text='Write the name in all lower case, no special characters and use - as blank spaces', max_length=100),
        ),
    ]
